apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  creationTimestamp: null
  name: core.platform-mesh.io
spec:
  resources:
  - group: core.platform-mesh.io
    name: authorizationmodels
    schema: v260112-5925c7e.authorizationmodels.core.platform-mesh.io
    storage:
      crd: {}
  - group: core.platform-mesh.io
    name: identityproviderconfigurations
    schema: v260123-dbda1fc.identityproviderconfigurations.core.platform-mesh.io
    storage:
      crd: {}
  - group: core.platform-mesh.io
    name: invites
    schema: v260212-65a62b6.invites.core.platform-mesh.io
    storage:
      crd: {}
  - group: core.platform-mesh.io
    name: stores
    schema: v250718-a64f278.stores.core.platform-mesh.io
    storage:
      crd: {}
status: {}
