apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: core.platform-mesh.io
spec:
  latestResourceSchemas:
  - v250718-a64f278.stores.core.platform-mesh.io
  - v251007-1d3512f.invites.core.platform-mesh.io
  - v251215-8997bd4.identityproviderconfigurations.core.platform-mesh.io
  - v260108-241afff.authorizationmodels.core.platform-mesh.io
status: {}
